### ISSUE TITLE
Programatically set SUMUP_API_KEY

### ISSUE THREAD

**Issue by steffanhalv** [mariusbackes/cordova-plugin-sumup#1]
Hi, this project looks great. :)

**I just have some questions:**

Can the SUMUP_API_KEY be set programatically within the cordova app or does it have to be set in the JAVA or Objective-C code? I see you have this set as an argument on installation, but we need to set this programatically using javascript. (The API KEY should be able to update on runtime for our use case)

Do you have any idea when we can expect an IOS version?
Will this only work for IONIC apps or also for other kind of cordova apps?

Thank you very much! @mariusbackes

**Comment by mariusbackes** [comment]
Hey,
I have edited the plugin. You can pass your SUMUP_API_KEY now from JavaScript and change it on runtime.

For a login you have now to use an object: 

`
SumUpKeys {
    accessToken: string;
    affiliateKey: string;
}

const sumUpKeys = new SumUpKeys();
`
Both values are empty strings. You can set your accessToken or affiliateKey just like you need it.

You can also use this Plugin with pure JavaScript and Cordova. You don't need an Ionic bases Project.

To reference the methods from the plugin just call window.SumUp.[methodName]
