### ISSUE TITLE
Crash at checkout

### ISSUE THREAD

**Issue by msokaily** [mariusbackes/cordova-plugin-sumup#16]
Hello,
I'm not connecting the sumup card reader device to my phone and when i try to make a payment the app crash without any exceptions.
This is the line where the app crashes.
        `runnable = () -> {
            SumUpAPI.checkout(cordova.getActivity(), payment, REQUEST_CODE_PAYMENT);
        };`

Is it because i'm not connecting the card reader device or something else, any suggestions ?!

Regards

**Comment by abutizi** [comment]
I too have the same problem. Did you manage to find a solution?
Care to share?

**Comment by Mokaily** [comment]
Hi, I didn't use this lib ..

i just did this ..

const browser = this.iab.create('sumupmerchant://pay/1.0?affiliate-key=' +
this.affiliateKey + '&callback=YOU-APP-SCHEMA://result&app-id=' + this.
app_id + '&total=' + this.total + '&currency=CHF&title=' + title +
'&skip-screen-success=true&receipt-mobilephone=&receipt-email=', '_system');
browser.hide();

and you have to activate deep link in your app to handle the result from
sumup app.

Best Wishes.

‫في الخميس، 23 ديسمبر 2021 في 8:20 م تمت كتابة ما يلي بواسطة ‪abutizi‬‏ <‪
***@***.***‬‏>:‬

**Comment by abutizi** [comment]
Thank you @Mokaily 

I appreciate your reply and will give your method a try !

All best
