### ISSUE TITLE
iOS unable to load stylesheet

### ISSUE THREAD

**Issue by zankle95** [mariusbackes/cordova-plugin-sumup#2]
Great work on this plugin! I know iOS is still not fully supported but there's an issue with loading stylesheets when calling up the login screen. This is the error thrown in the xcode console:

MyApp[2068:864770] +[SDSStyleSheet styleSheetFromURL:] (line 194): Could not load style sheet data from URL: (null)

I'm using the ionic v1 framework so just plain javascript, on the android side it works fine. I tried with the cordova-ionic-webview plugin installed and not (maybe it's a whitelist issue) but the situation doesn't change.

The login screen shows up with a transparent background and no style whatsoever.

Hope to see iOS support added soon! Thank you :)

**Comment by mariusbackes** [comment]
Hey,

like you said, it still doesn't support iOS but I will look for support as soon as possible.

**Comment by PepeBel4** [comment]
Hi Marius,
Would like to ask if iOS is still foreseen in the (near) future?
